name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_name: ${{ steps.prep.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Image Tag
        id: prep
        run: |
          REPO="${{ github.repository }}"
          LOWER_REPO="${REPO,,}"
          IMAGE="ghcr.io/${LOWER_REPO}/frontend:latest"
          echo "image=${IMAGE}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug env
        run: |
          echo "Length of secret: ${#VITE_API_BASE_URL}"
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.prep.outputs.image }}
          no-cache: true
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      IMAGE: ${{ needs.build.outputs.image_name }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin
            docker pull ${{ needs.build.outputs.image_name }}
            cd ${{ secrets.COMPOSE_DIR }}
            FRONTEND_IMAGE=${{ needs.build.outputs.image_name }} docker compose up -d --force-recreate --no-deps --pull always frontend
          EOF
